### ISSUE TITLE
Smart color scale

### ISSUE THREAD

**Issue by hsuominen** [giulioungaretti/opendatahacklab2014#11]
To make the data stand out more and look better I propose:

We make a quick histogram of the index score for some given slider configuration (bins are some given range of index scores). Then we select 5 bins that best represent the data and use that for the color map (colors can be the same, but ranges are changed dynamically).

Whatcha think?

**Comment by guenp** [comment]
so you mean you make a histogram of the entire map and then omit the tails?
how do you translate the histogram back to a heat map?

**Comment by hsuominen** [comment]
We have a discrete colorscale that maps easily to some 'smart bin' that we calculate. However you made a good point in that finding a smart bin size from the data (or an overbinned histogram) is non-trivial. One option would be to use a Gaussian-Mixture-Model to extract some effective bin width (effectively a fit of a sum of Gaussians..) - see http://www.astroml.org/book_figures/chapter4/fig_GMM_1D.html or http://scikit-learn.org/stable/modules/density.html buuut this is a bit too involved for what I was thinking (I tried the GMM, it works, but definitely not inline and in javascript...)

**Comment by giulioungaretti** [comment]
I don't get what you are suggesting actually :)

—
Giulio Ungaretti

**Comment by hsuominen** [comment]
Ok simplest method that encapsulates my idea is - compute 5 bins with constant area (variable width) and use the boundaries as the colorscale boundaries. For fun reading see http://pubs.research.avayalabs.com/pdfs/ALR-2007-003-paper.pdf

I will post a demo later.

**Comment by giulioungaretti** [comment]
but that’s pretty much a quantile, isn’t ? 

—
Giulio Ungaretti

**Comment by hsuominen** [comment]
Closed with nice d3 quantile function which implements equal area bins
