### ISSUE TITLE
Commit (cd03215ab4) broken

### ISSUE THREAD

**Issue by hsuominen** [giulioungaretti/opendatahacklab2014#19]
Commit https://github.com/giulioungaretti/opendatahacklab2014/commit/cd03215ab4b5c917511d077a0beffb0befea4c90 is broken

TypeError: Cannot read property '_leaflet_id' of undefined {stack: (...), message: "Cannot read property '_leaflet_id' of undefined"} main.js:276
Uncaught TypeError: Cannot set property 'innerHTML' of null main.js:95

**Comment by giulioungaretti** [comment]
?   commit has just an updated .gitignore...

**Comment by hsuominen** [comment]
Referencing commits is weird - the correct commit is 17be6ce996b3b8d44481f5738edd890ac2c53ab5 in the radar branch

**Comment by giulioungaretti** [comment]
ahm I see, it works for me though.

**Comment by giulioungaretti** [comment]
10d46752f20174daed309f1d27d0aaa50222cdc9  closes #19 , does it @hsuominen  ?

**Comment by hsuominen** [comment]
Still get error 
TypeError: Cannot read property '_leaflet_id' of undefined {stack: (...), message: "Cannot read property '_leaflet_id' of undefined"} 
But everything seems to work as expected

**Comment by giulioungaretti** [comment]
that's ok, it's a log message right ?
I am removing a layer that does not exit. May be fixed, when we have to optmium parameters loading the map when the browser si opened fisrt!
