### ISSUE TITLE
Implement interpolation algorithm to deal with missing data

### ISSUE THREAD

**Issue by hsuominen** [giulioungaretti/opendatahacklab2014#8]

**Comment by hsuominen** [comment]
Demo attached
![interpolation-01](https://cloud.githubusercontent.com/assets/5559036/4569955/04a1c0e2-4f54-11e4-9cae-24a1c0619da4.png)

**Comment by giulioungaretti** [comment]
Too bad for JET.

—
Giulio Ungaretti

**Comment by hsuominen** [comment]
Current status attached for the three interpolatable datasets (cars, bikes, parking) - looks like we only have parking data within the central ring - not how if it makes sense to extrapolate out so the interpolated results are omitted for now.

Also theres a weird (huge) peak in all data sets around the fisketorv area - maybe it's real. Let me know if you have any comments.

![interpolation_overview_page_1](https://cloud.githubusercontent.com/assets/5559036/4671827/8f61d748-5586-11e4-8538-46bbb71586ff.png)
![interpolation_overview_page_2](https://cloud.githubusercontent.com/assets/5559036/4671828/94b5d4c4-5586-11e4-8311-aefbfc1c669d.png)
