### ISSUE TITLE
cool histrogram widget below the hover information.

### ISSUE THREAD

**Issue by giulioungaretti** [giulioungaretti/opendatahacklab2014#9]
The idea here was to give an overall histogram of values computed for each dataset and highlight the histogram bin on the region over which the mouse hovers.

**Comment by giulioungaretti** [comment]
what about something like this

![img](http://red-badger.com/blog/wp-content/uploads/2014/02/spider-dos.gif)

**Comment by guenp** [comment]
yes please!

**Comment by hsuominen** [comment]
Giulio's suggestion is simpler and reduces clutter to the original suggestion - we can use this template for implementation https://github.com/alangrafu/radar-chart-d3

**Comment by giulioungaretti** [comment]
👍

—
Giulio Ungaretti

**Comment by giulioungaretti** [comment]
Implemented.
